### ISSUE TITLE
World creation problem

### ISSUE THREAD

**Issue by hermesdll** [hachchch/Geneciv#15]
When creating the world I encountered this problem:  
java.lang.NullPointerException
	at com.unciv.logic.civilization.Civilization.getPreferredVictoryTypeObjects(Civilization.kt:371)
	at com.unciv.logic.civilization.Civilization.setTransients(Civilization.kt:721)
	at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:650)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:113)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:105)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:151)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:105)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:304)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(Unknown Source:8)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:295)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:50)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:229)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(Unknown Source:8)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by hachchch** [comment]
solved with new version, maybe

**Comment by hermesdll** [comment]
nothing seems to have changed

**Comment by hachchch** [comment]
victorytypes.json Updated
Please try the new version. It'll probably work i guess.

**Comment by hermesdll** [comment]
Updated, but nothing changed

**Comment by hachchch** [comment]
Eh, I have no idea what is wrong with this mod. currently, I can only do changing something randomly to fix this problem... sorry man.
